### ISSUE TITLE
lsp-ivy endgame

### ISSUE THREAD

**Issue by yyoncho** [emacs-lsp/lsp-ivy#1]
We need:

1. Readme 
2. Melpa onboarding

@sebastiansturm willing to work on that?

**Comment by sebastiansturm** [comment]
sure. Doesn't sound like much work, maybe I'll get to it this weekend

**Comment by yyoncho** [comment]
@sebastiansturm are we on melpa?

**Comment by sebastiansturm** [comment]
argh, no. Sorry. I had only checked the list of packages offered to me by `list-packages`, pretty moronic in hindsight :/

**Comment by sebastiansturm** [comment]
closed via melpa/melpa#6471
