### ISSUE TITLE
How to select multiple fields in "Generate toString()" action

### ISSUE THREAD

**Issue by zaynetro** [emacs-lsp/lsp-ivy#28]
```
2  Select fields to include
> one: String
  two: String
```

If I hit Enter then only one field will be selected for the method. Which keybinding could I use for selecting multiple or all fields from the list?

**Comment by yyoncho** [comment]
see https://github.com/emacs-lsp/lsp-java/pull/150#issuecomment-514543285

**Comment by zaynetro** [comment]
Thanks a lot! I'd like to improve docs about this topic. What would be a good place to include that?

**Comment by yyoncho** [comment]
I tested it with lsp-start-plain.el and after installing ivy-hydra it works fine. 

> What would be a good place to include that?

lsp-java readme.

**Comment by schoettkr** [comment]
Selecting multiple fields for things like "Generate toString()" or "lsp-java-generate-overrides" works via ivy-hydra. However, currently it is not possible for example in the case of "Generate constructors" to generate a single constructor for multiple fields(when using ivy). ivy-hydra calls the selected action e.g ```lsp-java-generate-overrides``` for _each_ marked candidate.
I think there is a need to have an additional distinguishing between actions which can be called multiple times for different candidates (as with ```lsp-java-generate-overrides```)  and actions which should be called once but possibly with different/multiple canidates , e.g. when generating a constructor.
Related https://github.com/emacs-lsp/lsp-java/issues/147, https://github.com/emacs-lsp/lsp-java/pull/150
