### ISSUE TITLE
Ability to navigate to a symbol by typing the symbol name.

### ISSUE THREAD

**Issue by ccidral** [emacs-lsp/lsp-ivy#35]
I've been using `lsp-treemacs-symbols` to navigate to symbols in the current namespace. It works pretty well for visualizing symbols defined in the namespace, but it is not as convenient to navigate to a particular symbol because it requires clicking on the symbol with the mouse. It would be great if there was a way to navigate/jump to a symbol in the current namespace by typing its name in the minibuffer, very similar to how `consult-lsp-symbols` works except that `consult-lsp-symbols` searches for symbols globally.

**Comment by yyoncho** [comment]
counsel-imenu?

**Comment by ccidral** [comment]
@yyoncho It took me some time to realize you actually meant `consult-imenu` instead of `counsel-imenu` 😄 Yeah `consult-imenu` works perfectly! I guess we can close this issue.

**Comment by yyoncho** [comment]
Yeah, I am helm user but I know that ivy has imenu support
