### ISSUE TITLE
lsp-ivy should not sort the results alphabetically 

### ISSUE THREAD

**Issue by yyoncho** [emacs-lsp/lsp-ivy#4]
The order of the elements should be preserved.

**Comment by sebastiansturm** [comment]
this is strange, when I use `lsp-ivy` the candidates don't get sorted alphabetically. And since I'm not passing a `:sort` option, that is the behavior I'd expect. Are you sure `lsp-ivy` does the sorting in your case?

**Comment by yyoncho** [comment]
I noticed that they are not in the same order as lsp-helm. I will check whether this is alphabetical sort or something else.

**Comment by yyoncho** [comment]
I was mistaken, it works as expected.
