### ISSUE TITLE
Custom faces instead of hard-coded values

### ISSUE THREAD

**Issue by donderom** [emacs-lsp/lsp-ivy#8]
It would be just awesome to be able to customize the faces of `symbol-kind`s (separate face per group or per kind?).
Inheriting `font-lock-*` faces as default will make it compatible with the most themes out there at least.

**Comment by sebastiansturm** [comment]
makes sense I guess. I just pushed that change, could you please test it?

**Comment by donderom** [comment]
It's much much better now, thanks! 👍
