### ISSUE TITLE
Correct results are only visible for a short time, if you type to quickly

### ISSUE THREAD

**Issue by TheBlob42** [emacs-lsp/lsp-ivy#9]
I noticed a strange behaviour with `lsp-ivy-workspace-symbol` and `lsp-ivy-global-workspace-symbol` when I enter the search string too rapidly:

![lsp-ivy](https://user-images.githubusercontent.com/6849129/78396498-ca4e8b00-75ef-11ea-8c5a-91f75195fe53.gif)

As you can see the correct result is shown for a short time before jumping to a more general result.

I had a look into the source of `lsp-ivy--workspace-symbol` and noticed that the `current-request-id` which is used to cancel any former lsp-request is always nil. Therefore I assume that the following happens:

- user types "S", request is sent out (request 1)
- user continues typing "tage", request is sent out (request 2)
- request 2 arrives shows the correct results for "Stage"
- request 1 arrives overwriting the former results, which is not what the users wants to see

I hope you understand what I mean :sweat_smile: 

I found that the :id value is only present after the request was sent out using `lsp-send-request-async` there I came up with the following solution, which has worked for me so far:

```
(defun lsp-ivy--workspace-symbol (workspaces prompt initial-input)
  "Search against WORKSPACES with PROMPT and INITIAL-INPUT."
  (let ((current-request-id nil))
    (ivy-read
     prompt
     (lambda (user-input)
       (with-lsp-workspaces workspaces
         (let ((request (lsp-make-request
                         "workspace/symbol"
                         (list :query user-input))))
           (when current-request-id
             (lsp--cancel-request current-request-id))
           ;; extract the request-id from the body after is has been sent
           (setq current-request-id
		 (plist-get
		  (lsp-send-request-async
		   request
		   (lambda (result)
		     (ivy-update-candidates (-remove 'lsp-ivy--filter-func result)))
		   :mode 'detached) :id))))
       0)
     :dynamic-collection t
     :require-match t
     :initial-input initial-input
     :action #'lsp-ivy--workspace-symbol-action
     :caller 'lsp-ivy-workspace-symbol)))
``` 

So far I could only test this with `lsp-java`, but I guess it should work for other language-servers as well. Maybe there is a better solution as I am not really familiar with the whole lsp-mode source code, but I am open for feedback and suggestions :blush:

**Comment by sebastiansturm** [comment]
thank you! That looks like a bug indeed. `lsp-send-request-async` modifies its `request` argument, so I just moved the `(setq current-request-id ...)` below `lsp-send-request-async`. Could you please verify that this resolves the issue (never had seen this, maybe clangd is too fast)? Thanks again!

**Comment by yyoncho** [comment]
FTR we now have :cancel-token param which handles this pattern.

**Comment by TheBlob42** [comment]
@sebastiansturm yes this is resolving my issue (and looks less cluttered than my code), thank you :+1: 
@yyoncho I have seen the :cancel-token parameter being mentioned in the lsp-mode source code quite often, but I never understood how I obtain such a token? :thinking: is there any documentation you could point me towards?

**Comment by yyoncho** [comment]
@TheBlob42 :cancel-token is an object that you pass to lsp-request-async call will tag the request so if you perform that call a second time it will automatically cancel the previous call. This pattern is very common in lsp-mode

**Comment by TheBlob42** [comment]
@yyoncho and I tried to understand the whole time where the token is generated and how to obtain it :see_no_evil: thanks for the clarification :+1: 
And many thanks in general for the really good work regarding the lsp-mode and everything around it :blush:

**Comment by sebastiansturm** [comment]
> FTR we now have :cancel-token param which handles this pattern.

thanks, this is much better. Will use this instead
